#!/bin/bash
#
# landevlist is a simple shellscript that displays the MAC and IPv4 addresses of
# all devices connected in a LAN. It is licensed under the MIT License, copy of
# which is given below.
#
#
# MIT License
#
# Copyright (c) 2025-Present Arijit Kumar Das <arijitkdgit.official@gmail.com>.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


nplus=43

show_help() {
    printf "Usage: landevlist\n"
    printf "Lists devices connected to the local network (LAN) with their MAC and IPv4 addresses.\n\n"
    printf "Output is formatted in a tabular structure for readability.\n"
    printf "Only devices with an active connection will be displayed.\n\n"
    printf "Copyright (c) 2025-Present Arijit Kumar Das <arijitkdgit.official@gmail.com> under MIT License.\n\n"
    exit 0
}

if [[ "$1" == "--help" || "$1" == "-help" ||
"$1" == "/help" || "$1" == "help" ]]; then
    show_help
fi

for cmd in ip awk tr printf; do
    if ! command -v "$cmd" &> /dev/null; then
        echo "landevlist: Required command '$cmd' not found."
        echo "Make sure these packages are installed:"
        echo "* gawk"
        echo "* coreutils"
        echo "* iproute2 (on Debian/Ubuntu/Arch), or"
        echo "  iproute (on RHEL/Fedora)"
        exit 1
    fi
done

printf '%*s\n' $nplus '' | tr ' ' '+'
printf "|      Device MAC     |    IPv4 Address   |\n"
printf '%*s\n' $nplus '' | tr ' ' '+'

ip -4 neigh show |
awk '/lladdr/ {
    for (i=1; i<=NF; i++)
        if ($i ~ /^[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){5}$/)
            printf "|  %-17s  |  %-15s  |\n", $i, $1
}'

printf '%*s\n' $nplus '' | tr ' ' '+'
